# Generated by Django 2.0 on 2020-02-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wordoid', '0002_auto_20200218_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='disble_post',
            new_name='publish',
        ),
    ]
