# Generated by Django 2.0 on 2020-02-19 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wordoid', '0004_auto_20200219_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
