# Generated by Django 2.0 on 2020-02-19 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wordoid', '0005_auto_20200219_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
