# Generated by Django 2.0 on 2020-02-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wordoid', '0006_auto_20200219_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
