# Generated by Django 2.0 on 2020-02-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wordoid', '0010_auto_20200219_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=False),
        ),
    ]
