# Generated by Django 2.0 on 2020-02-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wordoid', '0011_auto_20200219_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=False),
        ),
    ]
